def column_structure():
    listing_identifiers= ['id','listing_url', 'scrape_id', 'last_scraped','calendar_last_scraped',
                      'first_review','last_review',]
    listing_qualitative_factors = ['name', 'description','neighborhood_overview', 'picture_url','latitude', 
                               'longitude','calendar_updated','reviews_per_month']
    listing_characterisitics = [ 'neighbourhood','neighbourhood_cleansed',
                                'neighbourhood_group_cleansed','property_type','room_type', 
                                'accommodates', 'bathrooms_text','bathrooms', 'bedrooms', 'beds',
        'amenities','has_availability',
        'availability_30', 'availability_60', 'availability_90',
        'availability_365','minimum_nights', 'maximum_nights',
        'minimum_minimum_nights', 'maximum_minimum_nights',
        'minimum_maximum_nights', 'maximum_maximum_nights',
        'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm',]
    host_details = ['host_id','host_url','host_name', 'host_since', 'host_location', 
                    'host_about', 'host_thumbnail_url', 'host_picture_url','host_neighbourhood',
                    'host_listings_count','host_total_listings_count','host_has_profile_pic',]
    host_performance_parameters= ['host_response_time', 'host_response_rate', 
                                'host_acceptance_rate', 'host_verifications',
                                'host_identity_verified','host_is_superhost']
    earning_estimators=['price','number_of_reviews','number_of_reviews_ltm', 
                            'number_of_reviews_l30d',]
    earning_influencers=['review_scores_rating', 'review_scores_accuracy',
        'review_scores_cleanliness', 'review_scores_checkin',
        'review_scores_communication', 'review_scores_location',
        'review_scores_value','license', 'instant_bookable',]
    host_other_details= ['calculated_host_listings_count',
        'calculated_host_listings_count_entire_homes',
        'calculated_host_listings_count_private_rooms',
        'calculated_host_listings_count_shared_rooms',]
    return [listing_identifiers,
            listing_qualitative_factors,
            listing_characterisitics,
            host_details,
            host_performance_parameters,
            earning_estimators,
            earning_influencers,
            host_other_details]

l=0
for col in column_structure():
    l=l+len(col)

amenities = ['Luggage dropoff allowed',
 'Barbecue utensils',
 'Washer',
 'Children’s dinnerware',
 'Kitchen',
 'Lockbox',
 'Breakfast',
 'Hair dryer',
 'Laptop-friendly workspace',
 'Gaoking basics',
 'Dishwasher',
 "Bathtub'rden or backyard",
 'Waterfront',
 'Shower gel',
 'Room-darkening shades',
 'Single level home',
 'Dishes and silverware',
 'Long term stays allowed',
 'Wifi',
 'High chair',
 'Babysitter recommendations',
 'Pocket wifi',
 'Air conditioning',
 'Refrigerator',
 'Extra pillows and blankets',
 'Bed linens',
 'Smoke alarm',
 'Microwave',
 'Fire extinguisher',
 'Baby bath',
 'First aid kit',
 'Fireplace guards',
 'Baking sheet',
 'BBQ grill',
 'Stove',
 'Pack ’n Play/travel crib',
 'Coffee maker',
 'Baby monitor',
 'Free street parking',
 'Shampoo',
 'Essentials',
 'Patio or balcony',
 'Crib',
 'Cable TV',
 'Oven',
 'Indoor fireplace',
 'Hangers',
 'Dryer',
 'Beach essentials',
 'Hot water',
 'Cooking basics',
 'Dishwasher',
 'Beachfront',
 'Private entrance',
 'TV',
 'Children’s books and toys',
 'Ethernet connection',
 'Heating',
 'Carbon monoxide alarm',
 'Iron',
 'Changing table',
 'Outlet covers',
 'Bathtub']